### ISSUE TITLE
Handle {{TextPlaceholders}}

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/starter-page-templates#21]
Our vertical templates come filled with generic content and in some places, they use text placeholders which should be replaced with data from the current site. Examples are `{{CompanyName}}`, `{{Address}}` or `{{Phone}}`. We need to handle these in our code too.

The technical solution seems to be easy, using https://github.com/janl/mustache.js or just plain regexp due to the limited possibilities. 

What I'm not certain about is if we have a dictionary available that has those pieces of data users might have filled during signup (I assume it comes from there). If we have it, where is it? Maybe site options? 

And what should we do in cases where we don't have such data? Fallback string like `{{Company Name}}` becomes "Your Company Name"?

Todos: 
- [x] Replacing placeholders with default value done in #22.
- [x] Replacing placeholders with real data from sites in #23.

**Comment by getdave** [comment]
Mustache template replace is definitely an option.

Alternatively, could this happen in the API layer? We could pass the data about the site to the API which then fills in the Template and sends back the block data to be inserted?

**Comment by michaeldcain** [comment]
> or just plain regexp

It's [handled on the backend](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/headstart/class-headstart-getters.php#181) via Headstart.

> What I'm not certain about is if we have a dictionary available that has those pieces of data users might have filled during signup (I assume it comes from there). If we have it, where is it? Maybe site options?

The defaults for the values are in the method linked above (and would need to be abstracted for use elsewhere). We stopped collecting address and phone number in Signup as a result of testing the new flow, but when available, they're stored as the `site_contact_info` array in a site option. We can use that as the source of truth for sites.

- `{{Company Name}}` is actually just an alias for the site's title (`blogname` option).

I'd suggest keeping the site options the same, but if we need to update the handlebar values in the vertical sites to be clearer/more declarative (i.e. `{{site_title}}` instead of `{{Company Name}}` and `{{site_contact_info.address}}` instead of `{{Address}}`), now would be the time to do it.

/cc @adamziel @ramonjd to follow this discussion and make sure the appropriate Signup/Headstart/Vertical content is updated

**Comment by marekhrabe** [comment]
Great to know it's super limited with only three options - that sounds like a job for regular text replace instead of bringing in some templating engine.

I don't think we want any changes on your side. We can handle it this way without a problem. Thanks for sharing details!

**Comment by marekhrabe** [comment]
Default values handled, working on real data soon. 

I've added a todo list into the issue description to reflect this.
